version: '3'
networks:
  default:
    external:
      name: platform_default

services:

  order-service:
    image: drip-cloud-demo/order-service
    container_name: order-service
    ports:
     - "80:8080"

  client-service:
    image: drip-cloud-demo/client-service
    container_name: client-service
    ports:
     - "81:8080"


